#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Finder\Finder;

$finder = new Finder();

$pharFile = 'configurator.phar';

// clean up
if (file_exists($pharFile)) {
    unlink($pharFile);
}

if (file_exists($pharFile . '.gz')) {
    unlink($pharFile . '.gz');
}

// create phar
$phar = new Phar($pharFile);

// start buffering. Mandatory to modify stub to add shebang
$phar->startBuffering();

// Create the default stub from main.php entrypoint
$defaultStub = $phar->createDefaultStub('bin/console');

foreach ($finder->files()->in(__DIR__)->path(['app/', 'bin/', 'vendor/']) as $file) {
    $phar->addFile($file->getRelativePathname());
}

//$phar->buildFromDirectory(__DIR__ . '/app');
//$phar->buildFromDirectory(__DIR__ . '/vendor');

// Customize the stub to add the shebang
$stub = "#!/usr/bin/php " . PHP_EOL . $defaultStub;

// Add the stub
$phar->setStub($stub);

$phar->stopBuffering();

// plus - compressing it into gzip
$phar->compressFiles(Phar::GZ);

# Make the file executable
chmod(__DIR__ . '/' . $pharFile, 0770);

echo "$pharFile successfully created" . PHP_EOL;
